// ignore_for_file: annotate_overrides

import "en.dart";

class Ar implements En {
  Direction $direction = Direction.rtl;
  String $name = "العربية";
  String $code = "ar";

  Map<String, String> dictionary = {
    // common
    "cancel": "إلغاء",
    "close": "غلق",
    "save": "حفظ",
    "reset": "إعادة تعيين",
    "continue": "استمر",
    "add": "إضافة",
    "edit": "تعديل",
    "delete": "حذف",
    "archive": "أرشفة",
    "restore": "استعادة",
    "logout": "خروج",
    "noResultsFound": "لم يتم العثور على نتائج",
    "startTyping": "اكتب هنا",
    "home": "الرئيسية",
    "calendar": "الرزنامة",
    "gettingImages": "يتم تحميل الصور",
    "more": "المزيد",
    "howToUse": "كيفية الإستخدام",

    // new
    "newPatient": "مريض جديد",
    "newAppointment": "موعد جديد",
    "newLabwork": "عمل مخبري جديد",
    "newNote": "ملاحظة جديدة",
    "newSupplier": "مزود جديد",
    "newOrder": "طلبية جديدة",
    "newUser": "مستخدم جديد",
    "newAdmin": "مدير جديد",

    // call
    "callLaboratory": "اتصل بالمختبر",
    "callPatient": "اتصل بالمريض",
    "emailDoctor": "ارسال بريد الكتروني",
    "callIssuer": "اتصل بالبائع",

    // screens
    "settings": "إعدادات",
    "dashboard": "الرئيسية",
    "appointments": "مواعيد",
    "patients": "مرضى",
    "doctors": "الاطباء",
    "labworks": "أعمال المختبر",
    "insights": "إحصائيات",

    // dashboard
    "admin": "مدير",
    "fullStats": "إحصائيات كاملة",
    "payments": "مدفوعات",
    "appointmentsToday": "المواعيد اليوم",
    "patientsToday": "المرضى اليوم",
    "newPatientsToday": "مرضى جدد اليوم",
    "paymentsMadeToday": "المدفوعات اليوم",
    "modeAdmin": "الوضع الإداري",
    "modeUser": "وضع المستخدم",
    "modeOffline": "وضع عدم الاتصال",
    "onceConnectionIsStable":
        "عندما يصبح اتصالك مستقرًا، يمكنك استخدام الزر في الزاوية اليمنى العليا لإعادة الاتصال.",
    "unRestrictedAccess": "وصول غير مقيد في التطبيق",
    "restrictedAccess": "وصول مقيد إلى بعض الصفحات كما يحدده المسؤول",
    "youAreCurrentlyIn": "أنت حاليًا في",
    "mode": "الوضع",
    "youHave": "لديك",
    "hello": "مرحبا",

    // datatable
    "archiveSelected": "أرشفة المحدد",
    "searchPlaceholder": "بحث...",
    "showHideArchived": "إظهار/إخفاء المؤرشفة",
    "showing": "يتم إظهار",
    "showMore": "إظهار المزيد",
    "by": "بحسب",
    "byName": "بحسب الإسم",
    "byDate": "بحسب التاريخ",
    "noItemsFound": "لم يتم العثور على عناصر",
    "filter": "تصفية",

    // doctors
    "doctor": "طبيب",
    "newDoctor": "طبيب جديد",
    "doctorDetails": "تفاصيل الطبيب",
    "pastAppointments": "المواعيد السابقة",
    "upcomingAppointments": "المواعيد القادمة",
    "doctorName": "اسم الطبيب",
    "doctorEmail": "بريد الطبيب الإلكتروني",
    "dutyDays": "أيام العمل",
    "addAppointment": "إضافة موعد",
    "lockToUsers":
        "يمكن فقط للمستخدمين التاليين الوصول لمعلومات ومواعيد الطبيب وتعديلها",
    "noUpcomingAppointmentsForThisDoctor":
        "لا يوجد مواعيد قادمة مسجلة لهذا الطبيب، استخدم الزر ادناه لتسجيل موعد جديد",

    // days and months
    "monday": "الاثنين",
    "tuesday": "الثلاثاء",
    "wednesday": "الأربعاء",
    "thursday": "الخميس",
    "friday": "الجمعة",
    "saturday": "السبت",
    "sunday": "الأحد",
    "january": "يناير",
    "february": "فبراير",
    "march": "مارس",
    "april": "أبريل",
    "may": "مايو",
    "june": "يونيو",
    "july": "يوليو",
    "august": "أغسطس",
    "september": "سبتمبر",
    "october": "أكتوبر",
    "november": "نوفمبر",
    "december": "ديسمبر",

    // appointment card
    "appointment": "موعد",
    "patient": "مريض",
    "photos": "صور",
    "pre-opNotes": "م. قبل العمل",
    "post-opNotes": "م. بعد العمل",
    "prescription": "وصفة طبية",
    "pay": "دفع",
    "paid": "مدفوع",
    "price": "السعر",
    "underpaid": "دفع ناقص",
    "overpaid": "دفع زائد",
    "fullyPaid": "كامل",
    "includesOtherAppointments":
        "هذا الإجمالي يعكس أيضًا المدفوعات الخاصة بمواعيد أخرى.",
    "paymentSummary": "ملخص الدفع",
    "editingAppointment": "تعديل الموعد",
    "after": "بعد",
    "days": "أيام",
    "day": "يوم",
    "isDone": "تم الانتهاء منه",
    "addLabwork": "إضافة عمل مختبري لهذا الموعد",
    "labworksForThisAppointment": "العمل المختبري الخاص بهذا الموعد",

    // patients
    "patientDetails": "تفاصيل المريض",
    "age": "العمر",
    "gender": "الجنس",
    "lastVisit": "آخر زيارة",
    "nextVisit": "الزيارة القادمة",
    "totalPayments": "إجمالي المدفوعات",
    "daysAgo": "أيام مضت",
    "noVisits": "لا توجد زيارات",
    "addNewPatient": "إضافة مريض جديد",
    "name": "الاسم",
    "birthYear": "سنة الميلاد",
    "phone": "الهاتف",
    "noValidNumbersFound": "لم يتم العثور على ارقام هاتف صالحة",
    "theFollowingPhoneNumbersAreDetected": "تم إيجاد الارقام التالية فقط",
    "email": "البريد الإلكتروني",
    "address": "العنوان",
    "notes": "ملاحظات",
    "patientTags": "سمات المريض",
    "male": "ذكر",
    "female": "أنثى",
    "noAppointmentsFound":
        "لم يتم العثور على مواعيد لهذا المريض، استخدم الزر أدناه لإضافة موعد جديد.",
    "editPatient": "تعديل المريض",
    "editAppointment": "تعديل الموعد",
    "patientPage": "صفحة ويب المريض",
    "patientCanUseTheFollowing":
        "يمكن للمريض استخدام الرابط التالي للوصول إلى مواعيده ومدفوعاته وصوره.",
    "web": "الويب",
    "telegram": "التيليجرام",
    "printQR": "طباعة الرمز",
    "dentalNotes": "الملاحظات السنية",
    "showPrimary": "إظهار اللبني",
    "showPermanent": "إظهار الدائم",
    "primary": "سن لبني",
    "permanent": "سن دائم",
    "lower": "سفلي",
    "upper": "علوي",
    "left": "يسار",
    "right": "يمين",
    "centralIncisor": "قاطع وسطي",
    "lateralIncisor": "قاطع جانبي",
    "canine": "ناب",
    "firstPremolar": "ضاحك أول",
    "secondPremolar": "ضاحك ثاني",
    "firstMolar": "رحاة اولى",
    "secondMolar": "رحاة ثانية",
    "thirdMolar": "رحاة ثالثة",
    "exportSelected": "تصدير المحدد",
    "export": "تصدير",
    "exportImportFeatureExplanation":
        "لنقل بيانات المرضى والمواعيد المحددة بين الخوادم أو التطبيقات الأخرى، قم بتصدير CSV من الخادم المصدر واستيراده إلى الخادم أو التطبيق الهدف.",
    "qrCode": "رمز المريض",
    "share": "مشاركة",
    "noPatientsSelected": "لم يتم اختيار أي مرضى",

    // communication
    "contact": "اتصال",
    "sendEmail": "إرسال بريد",
    "whatsapp": "واتساب",
    "call": "اتصال هاتفي",
    "text": "رسالة نصية",
    "countryCode": "الرمز الدولي",
    "countryCode_desc":
        "اختر الرمز الدولي الافتراضي عند إجراء المكالمات أو إرسال الرسائل",

    // treatments
    "treatment": "العلاج",
    "allTreatments": "كل العلاجات",
    "extraction": "قلع",
    "filling": "حشوة",
    "pulpotomy": "بضع لب",
    "rCT": "جذر",
    "other": "أخرى",
    "re-RCT": "إعادة جذر",
    "ortho": "تقويم",
    "whitening": "تبييض",
    "clean": "تنظيف",
    "implant": "زرعة",
    "surgery": "جراحة",
    "crown": "تاج",
    "veneer": "قشور",
    "bridge": "جسر",
    "overlay": "أوفرلاي",
    "temporary": "مؤقت",
    "tap the treatment you have performed to register it to the tooth":
        "إضغط على العلاج الذي تم اجراءه لتسجيله على السن",
    "tap the condition or history of the tooth to register it":
        "إضغط على الحالة او التاريخ المرضي للسن لتسجيله",
    "missing": "مفقود",
    "caries": "تسوس",
    "fractured": "كسر",
    "mobility": "حركة",
    "recession": "إنحسار",
    "rroot": "جذر متبفي",
    "rprimary": "لبني متبقي",
    "malposition": "سوء تموضع",
    "impacted": "مغمور",
    "abutment": "دعامة",
    "pontic": "طائف",

    // calendar (appointments)
    "allDoctors": "جميع الأطباء",
    "noAppointmentsForThisDay": "لا توجد مواعيد لهذا اليوم",
    "weekAbbr": "أسبوع",
    "twoWeeksAbbr": "أسبوعان",
    "monthAbbr": "شهر",
    "today": "اليوم",
    "date": "التاريخ",
    "changeDate": "تغيير التاريخ",
    "changeTime": "تغيير الوقت",
    "attention": "انتباه",
    "doctorNotAvailable":
        "قد لا يكون أحد الأطباء المحددين متاحًا في التاريخ المحدد.",
    "time": "الوقت",
    "preOperativeNotes": "ملاحظات ما قبل العملية",
    "selectDoctors": "اختيار الأطباء",
    "selectPatient": "اختيار المريض",
    "operativeDetails": "تفاصيل العملية",
    "postOperativeNotes": "ملاحظات ما بعد العملية",
    "extraInfoPlaceholder": "معلومات إضافية",
    "extraNotesFromAppointments": "ملاحظات إضافية من المواعيد:",
    "otherAppointmentsNotes": "ملاحظات مواعيد أخرى:",
    "printPrescription": "طباعة الوصفة الطبية",
    "priceIn": "السعر بـ",
    "paidIn": "مدفوع بـ",
    "gallery": "معرض الصور",
    "link": "رابط",
    "upload": "إختيار للرفع",
    "camera": "كاميرا",
    "emptyGallery": "معرض فارغ",
    "noPhotos": "لم يتم تحميل أي صور حتى الآن.",
    "importingPhotosFromLink": "استيراد الصور من الرابط",
    "useThisForm":
        "استخدم هذا النموذج لاستيراد الصور من روابط المشاركة، مثل صور جوجل، أو أي صفحة ويب قابلة للوصول تحتوي على صور ترغب في إضافتها إلى هذا الموعد.",
    "error": "خطأ",
    "enterLink": "أدخل عنوان URL الذي يحتوي على صور",
    "import": "استيراد",
    "otherPhotos": "صور من مواعيد أخرى",
    "draw": "رسم",
    "erase": "مسح",
    "showDrawings": "إظهار الرسومات",

    // labworks
    "laboratory": "مختبر",
    "month": "شهر",
    "labwork": "عمل المختبر",
    "labworkTitle": "عنوان عمل المختبر",
    "orderNotes": "ملاحظات الطلب",
    "unpaid": "غير مدفوع",
    "noSuggestions": "لا توجد اقتراحات",
    "received": "تم الاستلام من المختبر",
    "showDone": "إظهار المكتمل",
    "waitingForLab": "في انتظار المختبر",
    "undelivered": "غير مسلم للمريض",
    "receivedAndDelivered": "مكتمل",
    "selectPatientFirst": "يرجى اختيار المريض اولا",
    "patientHasNoAppointments": "لا يوجد مواعيد للمريض",
    "selectAppointment": "تحديد الموعد",
    "areYouSureYouWantTo": "هل انت متاكد من أنك تريد",

    // expenses
    "expense": "مصروف",
    "expenses": "مصاريف",
    "receipt": "وصل",
    "title": "العنوان",
    "cost": "التكلفة",
    "issuer": "البائع",
    "amount": "القيمة",
    "amountIn": "المبلغ بـ",
    "status": "الحالة",
    "due": "مستحق",
    "open": "فتح",
    "rename": "إعادة تسمية",
    "addSupplier": "إضافة مزود",
    "archiveSupplier": "أرشفة المزود",
    "items": "العناصر",
    "markAsPaid": "تسجيل كمدفوع",
    "markAsDue": "تسجيل كمستحق الدفع",
    "unpaidOrders": "طلبات مستحقة",
    "paymentHistory": "طلبات مدفوعة",
    "addOrder": "إضافة طلبية",
    "filterByItems": "تصفية حسب العناصر",
    "new": "جديد",
    "thisMonth": "هذا الشهر",
    "addPhoto": "إضافة صورة",
    "change": "تغيير",
    "empty": "فارغ",
    "totalDue": "المجموع المستحق",
    "notSet": "غير محدد",
    "photo": "صورة",
    "pickASupplier": "اختر مزود",
    "viewAllOrders": "عرض جميع الطلبيات",
    "lastOrder": "اخر طلبية",
    "supplier": "المزود",
    "orders": "طلبيات",

    // notes
    "addColumn": "إضافة عمود",
    "editColumn": "تعديل العمود",
    "columnTitle": "عنوان العمود",
    "columnColor": "لون العمود",
    "addNote": "إضافة ملاحظة",
    "editNote": "تعديل الملاحظة",
    "note": "ملاحظة",
    "recurrence": "تكرار",
    "isARecurrenceOfOlderNote": "هذا تكرار من ملاحظة اقدم",
    "recurringEvery": "تكرار كل",
    "recurring": "تكرار",
    "column": "عمود",
    "uncategorized": "غير مصنف",
    "relatingToPatient": "متعلق بالمريض",
    "assignedTo": "مرسل إلى",
    "dueDate": "تاريخ الاستحقاق",
    "attachments": "مرفقات",
    "archiveAllCompletedNotes": "أرشفة جميع الملاحظات المكتملة",
    "moveTowardsEnd": "تحريك نحو النهاية",
    "moveTowardsStart": "تحريك نحو البداية",
    "item": "عنصر",
    "addAttachment": "إضافة مرفق",
    "tapToDownload": "انقر لتحميل المرفق",
    "addComment": "إضافة تعليق",
    "sendComment": "ارسال",
    "tapToMarkAsPending": "تأشير كـ غير مكتمل",
    "tapToMarkAsDone": "تأشير كـ مكتمل",
    "archived": "مؤرشف",
    "overdue": "متأخر",
    "incoming": "مستلم لك",
    "outgoing": "صادر منك",
    "pending": "غير مكتمل",
    "completed": "مكتمل",
    "unassigned": "غير مرسل",
    "comments": "تعليقات",
    "createdDate": "تاريخ الإنشاء",
    "changeDueDate": "تغيير تاريخ الاستحقاق",
    "createdBy": "تم الإنشاء بواسطة",
    "switchAssignee": "تغيير المستلم",
    "noAssignee": "بدون ارسال",
    "sort": "ترتيب",
    "ascending": "تصاعدي",
    "descending": "تنازلي",
    "showAll": "عرض الكل",
    "showOnlyMine": "عرض ما يخصني فقط",
    "allAccounts": "جميع الحسابات",

    // stats
    "pickRange": "اختيار النطاق",
    "start": "بداية",
    "end": "نهاية",
    "weeks": "أسابيع",
    "months": "أشهر",
    "quarters": "ربع سنوي",
    "years": "سنوات",
    "year": "سنة",
    "appointmentsPer": "المواعيد بحسب",
    "paymentsAndExpensesPer": "المدفوعات والمصاريف بحسب",
    "newPatientsPer": "المرضى الجدد بحسب",
    "doneMissedPer": "المنجز والمفقود بحسب",
    "timeOfDay": "أوقات اليوم",
    "dayOfWeek": "أيام الاسبوع",
    "dayOfMonth": "أيام الشهر",
    "monthOfYear": "أشهر السنة",
    "patientsGender": "جنس المرضى",
    "total": "المجموع",
    "in_Duration_": "في",
    "acquiredPatientsIn": "المرضى المكتسبون في",
    "doneAndMissedAppointmentsIn": "المواعيد المنجزة والمفقودة في",
    "distributionOfAppointments": "توزيع المواعيد",
    "maleAndFemalePatients": "المرضى الذكور والإناث",
    "done": "منجز",
    "missed": "مفقود",
    "periodicity": "الدورية",

    // settings
    "currency": "العملة",
    "currency_desc":
        "رمز العملة المستخدم في جميع أنحاء التطبيق (مثل USD، EUR، IQD).",
    "phone_desc": "سيتم عرض رقم الهاتف في الطباعات وصفحة ويب المرضى.",
    "prescriptionFooter": "تذييل الوصفة الطبية",
    "prescriptionFooter_desc":
        "سيتم عرض هذا النص في اسفل الوصفة الطبية، يمكن استخدامه لوضع العنوان او رقم التسجيل النقابي.",
    "language": "اللغة",
    "language_desc":
        "لغة واجهة المستخدم للقوائم والأزرار والمعلومات المستخدمة في التطبيق.",
    "startingDayOfWeek": "يوم بداية الأسبوع",
    "startingDayOfWeek_desc": "اليوم الذي يبدأ فيه الأسبوع.",
    "dateFormat": "تنسيق التاريخ",
    "dateFormat_desc":
        "سيتم استخدام هذا التنسيق لعرض التواريخ حيثما كان ذلك ممكنًا.",
    "cacheReset": "الغاء التخزين المحلي",
    "cacheReset_desc":
        "يمكنك من خلال الزر ادناه الغاء التخزين المحلي للتطبيق - عدا الصور - لحل بعض المشاكل التي قد تواجهك اثناء المزامنة مع الأجهزة الأخرى.",
    "month/day/year": "شهر/يوم/سنة",
    "day/month/year": "يوم/شهر/سنة",
    "appliesTo": "ينطبق على",
    "all": "الكل",
    "you": "أنت",
    "system": "النظام",
    "initialSynchronization": "مزامة أولية",
    "synchronizing": "مزامنة مع الخادم",
    "clearingLocalData": "إزالة البيانات المحلية",
    "dentalNotation": "الترقيم السني",
    "dentalNotation_desc": "اختر نظام الترميز المفضل لديك",
    "palmer": "بالمر",
    "universal": "عالمي - أميريكي",
    "ISO": "أيزو",

    // advanced settings: Backups
    "backups": "النسخ الاحتياطي",
    "refresh": "تحديث",
    "download": "تحميل",
    "createNew": "إنشاء جديد",
    "restoreBackup": "استعادة النسخة الاحتياطية",
    "restoreBackupWarning1":
        "سيتم الكتابة فوق جميع البيانات في التطبيق حاليًا عند استعادة هذا النسخ الاحتياطي. أي تغييرات قمت بها بعد تاريخ هذا النسخ الاحتياطي",
    "restoreBackupWarning2":
        "ستضيع.\n\nهل أنت متأكد من أنك تريد استعادة هذا النسخ الاحتياطي؟",
    "sureDeleteBackup": "هل أنت متأكد من أنك تريد حذف هذا النسخ الاحتياطي",
    "backupDate": "تاريخ النسخ الاحتياطي",
    "useTheFollowingLinkToDownloadTheBackup":
        "استخدم الرابط التالي لتحميل النسخة الاحتياطية",
    "backups_config_title": "إعدادات النسخ الاحتياطي",
    "backups_config_desc":
        "تكوين جدول النسخ الاحتياطي التلقائي وإعدادات التخزين.",
    "backups_auto_enabled": "تفعيل النسخ التلقائي",
    "backups_cron": "الجدولة (cron)",
    "backups_cron_presets": "إعدادات مسبقة",
    "backups_cron_hourly": "كل ساعة",
    "backups_cron_6hours": "كل 6 ساعات",
    "backups_cron_12hours": "كل 12 ساعة",
    "backups_cron_daily": "يوميًا عند منتصف الليل",
    "backups_cron_daily3am": "يوميًا عند 3 صباحًا",
    "backups_cron_weekly": "أسبوعيًا (الأحد منتصف الليل)",
    "backups_cron_monthly": "شهريًا (اليوم 1 منتصف الليل)",
    "backups_cron_hint":
        "اختر جدولاً محدداً مسبقاً. سيتم ملء تعبير cron تلقائياً.",
    "backups_max_keep": "الحد الأقصى للنسخ المحفوظة",
    "backups_max_keep_hint": "سيتم حذف النسخ الأقدم عند تجاوز هذا الحد",
    "backups_s3_enabled": "تخزين النسخ في S3",
    "backups_save_success": "تم حفظ إعدادات النسخ الاحتياطي بنجاح",
    "backups_save_fail": "فشل حفظ إعدادات النسخ الاحتياطي",

    // Meta settings
    "meta_settings": "إعدادات التطبيق",
    "meta_info_title": "معلومات التطبيق العامة",
    "meta_info_desc":
        "قم بتكوين اسم التطبيق وعنوان URL وإعدادات العلامة التجارية.",
    "meta_appName": "اسم التطبيق",
    "meta_appName_hint": "يظهر في البريد الإلكتروني وعنوان شاشة تسجيل الدخول",
    "meta_appUrl": "رابط التطبيق",
    "meta_appUrl_hint": "يستخدم في البريد الإلكتروني والروابط المشتركة",
    "meta_save_success": "تم حفظ إعدادات التطبيق بنجاح",
    "meta_save_fail": "فشل حفظ إعدادات التطبيق",

    // Auth settings
    "auth_settings": "إعدادات المصادقة",
    "auth_info_title": "مدة الجلسة",
    "auth_info_desc":
        "حدد مدة صلاحية رموز المصادقة قبل أن يحتاج المستخدمون لتسجيل الدخول مرة أخرى.",
    "auth_users_duration": "جلسة المستخدم (أيام)",
    "auth_users_duration_hint":
        "عدد الأيام قبل أن يحتاج المستخدمون العاديون لإعادة تسجيل الدخول",
    "auth_superusers_duration": "جلسة المدير (أيام)",
    "auth_superusers_duration_hint":
        "عدد الأيام قبل أن يحتاج المدراء لإعادة تسجيل الدخول",
    "auth_save_success": "تم حفظ إعدادات المصادقة بنجاح",
    "auth_save_fail": "فشل حفظ إعدادات المصادقة",

    // advanced settings: Admins
    "admins": "المدراء",
    "accountCreated": "تم إنشاء الحساب",
    "editAdmin": "تعديل المدير",
    "validEmailMustBeProvided": "يجب تقديم بريد إلكتروني صالح",
    "password": "كلمة المرور",
    "leaveBlankToKeepUnchanged": "اتركه فارغًا للإبقاء عليه دون تغيير",
    "updatingPassword": "تحديث كلمة المرور",
    "leaveItEmpty": "اترك حقل كلمة المرور فارغًا إذا كنت لا تريد تغييره.",
    "minimumPasswordLength": "كلمة مرور من 10 أحرف على الأقل",

    // advanced settings: Users
    "users": "المستخدمين",
    "editUser": "تعديل المستخدم",

    // advanced settings: Permissions
    "permissions": "أذونات المستخدم",
    "usersCanAccess": "يمكن للمستخدمين الوصول إلى",
    "permissionsNotice":
        "تنطبق الأذونات التالية على المستخدمين المدرجين أعلاه والوصول غير المتصل. ومع ذلك، يتمتع المسؤولون مثلك بوصول غير مقيد في التطبيق، ما لم يكن غير متصل.",
    "restricted": "مقيد",
    "view": "عرض",
    "personal": "شخصي",
    "full": "وصول كامل",
    "local": "محلي فقط",
    "canUpload": "يمكنه الرفع",
    "cantUpload": "لا يمكنه الرفع",
    "accounts": "الحسابات",
    "account": "حساب",
    "user": "مستخدم",
    "operatesOnPatients": "يعمل على المرضى",

    // advanced settings: prod tests
    "prodTests": "اختبارات الإنتاج",
    "fileStorageTest": "اختبار تخزين الملفات",
    "fileStorageTestDesc":
        "استخدم الزر التالي لاختبار ما إذا كان تخزين S3 يعمل بشكل صحيح.",
    "fileStorageButton": "اختبار إعداد S3",
    "fileStorageFail": "فشل إعداد S3",
    "fileStorageSuccess": "إعداد S3 يعمل بشكل صحيح",

    // S3 settings
    "s3_settings": "إعدادات تخزين S3",
    "s3_info_title": "تكوين تخزين S3",
    "s3_info_desc":
        "قم بتكوين إعدادات التخزين المتوافق مع S3 لتحميل الملفات والنسخ الاحتياطية.",
    "s3_endpoint": "عنوان URL للنقطة النهائية",
    "s3_bucket": "اسم الحاوية",
    "s3_region": "المنطقة",
    "s3_accessKey": "مفتاح الوصول",
    "s3_secretKey": "المفتاح السري",
    "s3_secretKey_hint":
        "اتركه فارغًا للاحتفاظ بالقيمة الحالية. مفتاح الوصول السري S3 الخاص بك",
    "s3_enabled": "تفعيل تخزين S3",
    "s3_forcePathStyle": "فرض نمط المسار",
    "s3_forcePathStyle_hint":
        "استخدام عنونة نمط المسار بدلاً من النطاق الفرعي (مطلوب لـ Cloudflare R2)",
    "s3_endpoint_hint": "عنوان URL لنقطة النهاية لمزود S3",
    "s3_bucket_hint": "اسم حاوية S3 الخاصة بك",
    "s3_region_hint": "منطقة الحاوية، أو 'auto' لـ Cloudflare R2",
    "s3_accessKey_hint": "معرف مفتاح الوصول S3 الخاص بك",
    "s3_test_success": "إعداد S3 يعمل بشكل صحيح",
    "s3_test_fail": "فشل اختبار إعداد S3",
    "s3_save_success": "تم حفظ إعدادات S3 بنجاح",
    "s3_save_fail": "فشل حفظ إعدادات S3",
    "test": "اختبار",

    // SMTP settings
    "smtp_settings": "إعدادات البريد SMTP",
    "smtp_info_title": "تكوين بريد SMTP",
    "smtp_info_desc":
        "قم بتكوين إعدادات SMTP لإرسال البريد الإلكتروني (إعادة تعيين كلمة المرور، الإشعارات، إلخ).",
    "smtp_host": "الخادم",
    "smtp_port": "المنفذ",
    "smtp_username": "اسم المستخدم",
    "smtp_password": "كلمة المرور",
    "smtp_senderName": "اسم المرسل",
    "smtp_senderEmail": "بريد المرسل",
    "smtp_tls": "استخدام TLS",
    "smtp_tls_auto": "تلقائي (STARTTLS)",
    "smtp_tls_always": "دائم",
    "smtp_tls_hint": "تلقائي = STARTTLS (منفذ 587)\n دائم = SSL (منفذ 465)",
    "smtp_presets": "إعدادات مسبقة",
    "smtp_port_blocked_warning":
        "بعض مزودي الاستضافة (مثل DigitalOcean و Hetzner و Google Cloud) يحظرون منافذ SMTP افتراضيًا. تأكد من السماح بـ 587 أو 465، أو استخدم منفذًا مختلفًا.",
    "smtp_host_hint": "عنوان خادم SMTP لمزود البريد الإلكتروني",
    "smtp_port_hint": "587 أو 465",
    "smtp_username_hint": "عادة عنوان بريدك الإلكتروني الكامل",
    "smtp_password_hint":
        "اتركه فارغًا للاحتفاظ بالقيمة الحالية. استخدم كلمة مرور تطبيق إذا كانت المصادقة الثنائية مفعلة",
    "smtp_app_passwords": "كلمات مرور التطبيقات",
    "smtp_senderName_hint": "الاسم المعروض في حقل المرسل",
    "smtp_senderEmail_hint": "عنوان البريد الإلكتروني المعروض في حقل المرسل",
    "smtp_localName": "الاسم المحلي HELO/EHLO",
    "smtp_localName_hint": "يستخدم في تحية HELO/EHLO، عادة نطاقك",
    "smtp_enabled": "تفعيل SMTP",
    "smtp_test_success": "إعداد SMTP يعمل بشكل صحيح",
    "smtp_test_fail": "فشل اختبار إعداد SMTP",
    "smtp_save_success": "تم حفظ إعدادات SMTP بنجاح",
    "smtp_save_fail": "فشل حفظ إعدادات SMTP",

    "emailTest": "اختبار البريد الإلكتروني",
    "emailTestDesc":
        "استخدم الزر التالي لاختبار ما إذا كان خادمك يمكنه إرسال البريد الإلكتروني بشكل صحيح. يجب تسليم بريد إلكتروني يشبه إعادة تعيين كلمة المرور إلى عنوان البريد الإلكتروني المستهدف.",
    "targetEmail": "البريد الإلكتروني المستهدف",
    "emailTestButton": "إرسال بريد إلكتروني تجريبي",
    "emailTestFail": "فشل اختبار البريد الإلكتروني",
    "emailTestSuccess":
        "تم إرسال البريد الإلكتروني بنجاح، يرجى التحقق من بريدك الوارد.",
    "fail": "فشل",
    "success": "نجاح",

    // login
    "login": "تسجيل الدخول",
    "clear": "مسح",
    "resetPassword": "إعادة تعيين كلمة المرور",
    "serverUrl": "رابط الخادم",
    "proceedOffline": "بدون اتصال",
    "youLLGet": "ستصلك التعليمات عبر بريدك الالكتروني",
    "beenSent":
        "لقد تم ارسال رابط اعادة تعيين كلمة المرور الخاص بك عبر بريدك الالكتروني",

    // static notifications flyout
    "notifications": "الإشعارات",
    "enableNotifications": "تفعيل الإشعارات",
    "dueLabworks": "اعمال مختبر مستحقة",
    "undeliveredLabworks": "اعمال مختبر غير مسلمة",
    "outgoingNotes": "ملاحظات صادرة",
    "incomingNotes": "ملاحظات واردة",
    "appointmentsSetToday": "مواعيد اليوم",
    "labworksDue": "اعمال مختبر مستحقة",
    "labworksNotDelivered": "اعمال مختبر غير مسلمة",
    "outgoingPendingNotes": "ملاحظات صادرة مستحقة",
    "incomingPendingNotes": "ملاحظات واردة مستحقة",

    // patientSide
    "generateQRLink": "عمل صفحة للمراجع",
    "patientSide": "صفحة المراجع",

    // other
    "otherNotesPerAppointment":
        "هنالك ملاحظات اخرى مسجلة ضمن مواعيد محددة، تظهر في صفحة المواعيد ولا تظهر هنا.",
    "sureArchiveSelected": "هل انت متأكد من حذف العناصر المحددة؟",
    "sureClosePanel":
        "هل انت متأكد من اغلاق هذه النافذة؟ سيتم الغاء جميع التغييرات التي قمت بها",
    "sure": "متأكد",
    "back": "تراجع",
    "firstLaunchDialogTitle": "تم تنصيب البرنامج بنجاح",
    "firstLaunchDialogContent":
        "يمكنك الان استخدام البرنامج كما تحب. ولكن هنالك بعض الخطوات الاضافية التي يجب ان تتخذها من أجل تجربة مثالية أكثر ومن اجل الحفاظ على بياناتك من الفقدان. قم بمسح الكود التالي من خلال هاتفك لمعرفة المزيد.",
    "newVersionDialogTitle": "هنالك اصدار جديد متاح",
    "newVersionDialogContent":
        "يرجى تحديث التطبيق للحصول على أحدث الميزات والتطويرات الجديدة. قم بمسح الكود التالي لتحميل التحديث الجديد.",

    // login required
    "loginRequired": "تسجيل الدخول مطلوب",
    "loginRequiredDesc": "يرجى تسجيل الدخول للمتابعة",

    // server help flyout
    "whatIsAServer": "ما هو الخادم؟",
    "helpOnCreatingAServer":
        "يتيح لك الخادم تخزين بياناتك بأمان، وإجراء النسخ الاحتياطية، والمزامنة بين الأجهزة، والمزيد.",
    "createNewServer": "إنشاء خادم جديد",

    // when errors
    "errors": "أخطاء",
    "reconnect": "إعادة الاتصال",
    "uploadingAttachment": "رفع المرفق",
    "errorHappenedWhen": "حدث خطأ أثناء",
    "deletingPatientImageFromServer": "حذف صورة المريض من الخادم",
    "openingPatientImage": "فتح صورة المريض",
    "importingRemoteImages": "استيراد الصور عن بعد",
    "creatingNewAccount": "إنشاء حساب جديد",
    "updatingAccounts": "تحديث الحسابات",
    "loadingAccounts": "تحميل الحسابات",
    "openingFullPatientImage": "فتح صورة المريض الكاملة",
    "deletingAccount": "حذف الحساب",
    "uploadingPatientImageFromCamera": "رفع صورة المريض من الكاميرا",
    "uploadingPatientImageFromGallery": "رفع صورة المريض من المعرض",
    "deletingOrderImageFromServer": "حذف صورة الطلب من الخادم",
    "uploadingOrderImageFromGallery": "رفع صورة الطلب من المعرض",
    "uploadingOrderImageFromCamera": "رفع صورة الطلب من الكاميرا",
    "openingImageFromGrid": "فتح الصورة من الشبكة",
    "openingMultipleImagesFromGrid": "فتح الصور من الشبكة",
    "generatingPatientLink": "توليد رابط المريض",
    "gettingRemoteImagesList": "الحصول على قائمة الصور من الخادم",
    "sendingUpdatesToServer": "ارسال التحديثات للخادم",
    "deletingFile": "حذف الملف",
    "uploadingFile": "رفع الملف",

    // AI services
    "ai_services": "الخدمات الذكية",
    "ai_services_desc":
        "تفعيل أو تعطيل الميزات المدعومة بالذكاء الاصطناعي مثل مسح الفواتير والملاحظات الصوتية واستخراج تاريخ الأسنان.",
    "on": "تشغيل",
    "off": "إيقاف",
    "noCameraOrGallery": "لا توجد كاميرا أو معرض صور",

    // Receipt scanner
    "receipt_scanner_settings": "مسح الفواتير",
    "receipt_scanner_info_title": "مسح الفواتير بالذكاء الاصطناعي",
    "receipt_scanner_info_desc":
        "التقط صورة للفاتورة وسيقوم الذكاء الاصطناعي باستخراج الأصناف والأسعار وتفاصيل المورد.",
    "receipt_scanner_worker_url": "رابط الخدمة",
    "receipt_scanner_worker_url_hint":
        "نقطة نهاية ثابتة. تتم معالجة صور الفواتير بشكل آمن عبر Cloudflare Workers.",
    "receipt_scanner_auth_server": "خادم المصادقة",
    "receipt_scanner_auth_server_hint":
        "رابط خادم PocketBase المستخدم للمصادقة.",
    "receipt_scanner_test_success": "تم الاتصال بنجاح! تم الحصول على الرمز.",
    "receipt_scanner_test_fail": "فشل الاتصال",
    "scanReceipt": "مسح الفاتورة",
    "readFromPhoto": "قراءة من الصورة",
    "readingItemsFromPhoto": "قراءة الأصناف من الصورة",
    "scanningReceipt": "جاري مسح الفاتورة...",
    "receiptScanFailed": "فشل مسح الفاتورة",
    "testing": "جاري اختبار الاتصال...",
    "newSupplierWillBeAdded": "هذا المورد غير موجود وسيتم إضافته تلقائياً.",
    "unknown": "غير معروف",
    "scan_receipt_save_success": "تم حفظ الفاتورة بنجاح",
    "scan_receipt_save_fail": "فشل حفظ الفاتورة",
  };
}
