// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoXL7Wu7t2M4LkfhFFL-0HSvSquXXlU-Y',
    appId: '1:107363374876:web:24e632ad5e01bc67620cd9',
    messagingSenderId: '107363374876',
    projectId: 'apexo-14f90',
    authDomain: 'apexo-14f90.firebaseapp.com',
    storageBucket: 'apexo-14f90.firebasestorage.app',
    measurementId: 'G-T4YLG7D5EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuRbOixyXDU1GDcdsRhks9iE67zQ_d0MU',
    appId: '1:107363374876:android:94394fabaf3c6672620cd9',
    messagingSenderId: '107363374876',
    projectId: 'apexo-14f90',
    storageBucket: 'apexo-14f90.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoXL7Wu7t2M4LkfhFFL-0HSvSquXXlU-Y',
    appId: '1:107363374876:web:18f4bc0f9e83e1f6620cd9',
    messagingSenderId: '107363374876',
    projectId: 'apexo-14f90',
    authDomain: 'apexo-14f90.firebaseapp.com',
    storageBucket: 'apexo-14f90.firebasestorage.app',
    measurementId: 'G-W74EZWCJR4',
  );

}